apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hrsw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hrsw
    app.kubernetes.io/part-of: byoc-app-ihao
  name: hrsw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hrsw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hrsw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-bmdf-tenant/byoc-app-ihao/hrsw@sha256:4e1814b176a330e75538eb683cc4f0237996aba676a448d1b1b969c7fa000ce9
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
